---
settings:
  - { domain: com.apple.finder, key: AppleShowAllFiles, type: string, value: TRUE }
  - { domain: NSGlobalDomain, key: AppleShowAllExtensions, type: bool, value: TRUE }
  - { domain: NSGlobalDomain, key: InitialKeyRepeat, type: int, value: 20 }
  - { domain: NSGlobalDomain, key: KeyRepeat, type: int, value: 2 }
  - { domain: com.apple.dock, key: tilesize, type: float, value: 40 }
  - { domain: com.apple.dock, key: autohide, type: bool, value: TRUE }
  - { domain: com.apple.menuextra.battery, key: ShowPercent, type: string, value: YES }
  - { domain: com.apple.AppleMultitouchTrackpad, key: TrackpadCornerSecondaryClick, type: int, value: 2 }
  - { domain: com.apple.AppleMultitouchTrackpad, key: Clicking, type: int, value: 1 }
